### PR TITLE
Using Result replaced with Error Handling

### PR DESCRIPTION
**Pull request by Lokathor**
Expanded the Using Result article into a broader Error Handling article
that goes over Option, Result, and Panic. Updated the writing style to
assume that the reader is a Haskell user learning Rust, rather than a
Rust user looking to learn Haskell.

### CODE REVIEW

**Comment by Lokathor** [comment]
Whoops, I edited the article that the README.md talks about without also adjusting how the README.md talks about it. Suppose it'd also need an update as well.

**Comment by mgattozzi** [comment]
Hey @Lokathor do you mind doing that then before I merge this?

**Comment by Lokathor** [comment]
I do not mind, but I am not clear on how to edit a pull request once it has been made. If I have to I can just delete this pull request and do a new one, but I am not sure if there is a better way.

**Comment by mgattozzi** [comment]
@Lokathor It's really easy actually! On your branch you made on your fork just add more commits and they'll show up here. I can then do a squash and merge into one commit.

**Comment by Lokathor** [comment]
Ah, excellent. I will try to get to that this evening.

**Comment by mgattozzi** [comment]
Awesome looking forward to it!

**Comment by Lokathor** [comment]
I ended up doing a complete editing pass on the Readme, but I think it's got a little more punch now.

**Comment by mgattozzi** [comment]
@Lokathor Awesome! Sorry I've been busy with getting back to work with finals being finished yesterday. I'll give this a look over tomorrow and leave some review comments if I have any!

**Comment by mgattozzi** [comment]
I dropped the ball on this one so that's my bad. I'm at my annual National Guard training so when I get back I have this and a ton of other things to work through that I've not kept up on.

**Comment by mgattozzi** [comment]
Thanks for the PR @Lokathor!

**Pull request merged**
